### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by kmeng01** [jagdeepsb/autograd#1]
![image](https://user-images.githubusercontent.com/13970922/164154640-ba08076a-c93f-45e9-98a3-15d1d4eb77fa.png)

**Comment by kmeng01** [comment]
It's been 42.0 seconds. Why haven't I received a reply yet?

**Comment by jagdeepsb** [comment]
Have you tried factoring your joint? 
If it doesn't work reinstall windows.
